# Generated by Django 4.2.16 on 2024-11-03 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_debe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_haber', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('puesto', models.CharField(max_length=50)),
                ('horas_semanales', models.IntegerField()),
                ('pago_diario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('afp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('septimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('incaf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vacaciones', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aguinaldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_real_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='LibroMayor',
            fields=[
                ('id_libro_mayor', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PartidaDiaria',
            fields=[
                ('id_partida_diaria', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('id_libro_mayor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_diarias', to='Sistema.libromayor')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_operacion', models.DateField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('total_debe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_haber', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_partida_diaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='Sistema.partidadiaria')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cuenta', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('subcategoria', models.CharField(blank=True, max_length=50, null=True)),
                ('saldo_debe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_haber', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('id_asiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_contables', to='Sistema.asiento')),
            ],
        ),
        migrations.AddField(
            model_name='asiento',
            name='id_transaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='Sistema.transaccion'),
        ),
    ]
