# Generated by Django 4.2.16 on 2024-11-03 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0002_transaccion_contenido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentacontable',
            name='id_asiento',
        ),
        migrations.AddField(
            model_name='asiento',
            name='id_cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos', to='Sistema.cuentacontable'),
        ),
    ]
