# Generated by Django 4.2.16 on 2024-11-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0003_remove_cuentacontable_id_asiento_asiento_id_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacontable',
            name='saldado_acreedor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='saldado_deudor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
