# Generated by Django 4.2.16 on 2024-11-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0005_balancegeneral_estadodecapital_estadoderesultado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancegeneral',
            name='activos',
        ),
        migrations.RemoveField(
            model_name='balancegeneral',
            name='pasivos',
        ),
        migrations.RemoveField(
            model_name='balancegeneral',
            name='patrimonio',
        ),
        migrations.RemoveField(
            model_name='estadodecapital',
            name='patrimonio_final',
        ),
        migrations.RemoveField(
            model_name='estadoderesultado',
            name='costos_venta',
        ),
        migrations.RemoveField(
            model_name='estadoderesultado',
            name='ingresos_operativos',
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='activos_debe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='activos_haber',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='activos_saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='pasivos_debe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='pasivos_haber',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='pasivos_saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='patrimonio_debe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='patrimonio_haber',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='patrimonio_saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='estadodecapital',
            name='patrimonio_final_debe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='estadodecapital',
            name='patrimonio_final_haber',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='estadodecapital',
            name='patrimonio_final_saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='estadoderesultado',
            name='costos_venta_debe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='estadoderesultado',
            name='costos_venta_haber',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='estadoderesultado',
            name='costos_venta_saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='estadoderesultado',
            name='ingresos_operativos_debe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='estadoderesultado',
            name='ingresos_operativos_haber',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='estadoderesultado',
            name='ingresos_operativos_saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
