# Generated by Django 4.2.16 on 2024-11-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0006_remove_balancegeneral_activos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancegeneral',
            name='balance_general_debe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='balance_general_haber',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
