# Generated by Django 4.2.16 on 2024-11-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0007_balancegeneral_balance_general_debe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='costo_real_mensual',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='horas_semanales',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='pago_diario',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='salario',
        ),
        migrations.AddField(
            model_name='empleado',
            name='costo_real_semanal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='empleado',
            name='dias_semanales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empleado',
            name='salario_nominal_diario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
