# Generated by Django 4.2.16 on 2024-11-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0008_remove_empleado_costo_real_mensual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentasestadoderesultado',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='cuentasestadoderesultado',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='cuentasestadoderesultado',
            name='id_estado_resultado',
        ),
        migrations.RemoveField(
            model_name='cuentasestadoderesultado',
            name='saldo_acreedor',
        ),
        migrations.RemoveField(
            model_name='cuentasestadoderesultado',
            name='saldo_deudor',
        ),
        migrations.AddField(
            model_name='cuentasestadoderesultado',
            name='saldado_acreedor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cuentasestadoderesultado',
            name='saldado_deudor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cuentasestadoderesultado',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cuentasestadoderesultado',
            name='saldo_debe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cuentasestadoderesultado',
            name='saldo_haber',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
