# Generated by Django 4.2.16 on 2024-11-04 21:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0009_remove_cuentasestadoderesultado_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentasestadoderesultado',
            name='saldado_acreedor',
        ),
        migrations.RemoveField(
            model_name='cuentasestadoderesultado',
            name='saldado_deudor',
        ),
        migrations.RemoveField(
            model_name='cuentasestadoderesultado',
            name='saldo',
        ),
        migrations.RemoveField(
            model_name='cuentasestadoderesultado',
            name='saldo_debe',
        ),
        migrations.RemoveField(
            model_name='cuentasestadoderesultado',
            name='saldo_haber',
        ),
        migrations.AddField(
            model_name='cuentasestadoderesultado',
            name='categoria',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuentasestadoderesultado',
            name='codigo',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuentasestadoderesultado',
            name='id_estado_resultado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='Sistema.estadoderesultado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuentasestadoderesultado',
            name='saldo_acreedor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cuentasestadoderesultado',
            name='saldo_deudor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.CreateModel(
            name='CuentasAuxiliaresEstadoDeResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('saldo_debe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_haber', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldado_acreedor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldado_deudor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('id_estado_resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_auxiliares', to='Sistema.estadoderesultado')),
            ],
        ),
    ]
