# Generated by Django 4.2.16 on 2024-11-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0010_remove_cuentasestadoderesultado_saldado_acreedor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadoderesultado',
            name='costos_venta_debe',
        ),
        migrations.RemoveField(
            model_name='estadoderesultado',
            name='costos_venta_haber',
        ),
        migrations.RemoveField(
            model_name='estadoderesultado',
            name='costos_venta_saldo',
        ),
        migrations.RemoveField(
            model_name='estadoderesultado',
            name='ingresos_operativos_debe',
        ),
        migrations.RemoveField(
            model_name='estadoderesultado',
            name='ingresos_operativos_haber',
        ),
        migrations.RemoveField(
            model_name='estadoderesultado',
            name='ingresos_operativos_saldo',
        ),
        migrations.RemoveField(
            model_name='estadoderesultado',
            name='utilidad_bruta',
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='detalle',
            field=models.CharField(default='Usuario', max_length=50),
            preserve_default=False,
        ),
    ]
