# Generated by Django 4.2.16 on 2024-11-05 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0011_remove_estadoderesultado_costos_venta_debe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentasAuxiliaresEstadoDeCapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('saldo_debe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_haber', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldado_acreedor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldado_deudor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('id_estado_resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_auxiliares_estado_de_capital', to='Sistema.estadoderesultado')),
            ],
        ),
    ]
