# Generated by Django 4.2.16 on 2024-11-05 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0012_cuentasauxiliaresestadodecapital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuentasauxiliaresestadodecapital',
            old_name='id_estado_resultado',
            new_name='id_estado_capital',
        ),
    ]
