# Generated by Django 5.1.2 on 2024-11-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0016_remove_estadodecapital_patrimonio_final_debe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=100)),
                ('duracion_proyecto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('costo_materiales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ganancia_bruta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
